## Flask app 配置
flask_app:
  DEBUG: false

## Flask app server 配置
app_server:
  host: "127.0.0.1"
  port: 5001

## 数据库连接池配置
database_connection_pool:
  # 数据库ip地址
  host: "192.168.64.16"
  # 库名
  db: "data_visualization"
  # 用户名
  user: "data_visualization"
  # 密码
  password: "123456"
  # 数据库端口
  port: 3306
  # 字符编码
  charset: "utf8mb4"
  # 连接池中空闲连接的初始数量
  min_cached: 10
  # 连接池中空闲连接的最大数量
  max_cached: 20
  # 共享连接的最大数量
  max_shared: 10
  # 创建连接池的最大数量
  max_connections: 100
  # 超过最大连接数量时候的表现（为 True 等待连接数量下降；为 False 直接报错处理）
  blocking: TRUE
  # 单个连接的最大重复使用次数（O 或 None 为无限制）
  max_usage: 100
  # 准备session的SQL语句列表(可选)（比如： ["set datestyle to ...", "set time zone ...", "SET AUTOCOMMIT = 1"]）
  set_session: ["SET AUTOCOMMIT = 1"]
  # 设定当连接用完返回到连接池时，该如何重置连接（为 False 或 None 时，回滚以 `connection.begin()` 开始的事务；为 True 时，始终为了安全起见发起回滚）
  reset: TRUE